name = "objectly"
compatibility_date = "2026-01-01"
main = "worker/index.ts"

[assets]
directory = "dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[r2_buckets]]
binding = "ICONS"
bucket_name = "objectly-icons"
